dof_fit:
    # Simulation settings for using moveit_sim_controllers
    moveit_sim_hw_interface:
      joint_model_group: hand
      joint_model_group_pose: open
    # ros_control_boilerplate Settings -----------------------
    # Settings for ros_control control loop
    generic_hw_control_loop:
      loop_hz: 300
      cycle_time_error_threshold: 0.01

    # Settings for ros_control hardware interface
    hardware_interface:
      joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
        - Joint_6
        - Gripper_Idol_Gear_Joint
        - Gripper_Servo_Gear_Joint
    sim_control_mode: 0 # 0: position, 1: velocity

    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    arm_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
        - Joint_6
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0
        Joint_1: {trajectory: 0.1, goal: 0.0}
        Joint_2: {trajectory: 0.1, goal: 0.0}
        Joint_3: {trajectory: 0.1, goal: 0.0}
        Joint_4: {trajectory: 0.1, goal: 0.0}
        Joint_5: {trajectory: 0.1, goal: 0.0}
        Joint_6: {trajectory: 0.1, goal: 0.0}
      gains:
        Joint_1: {p: 60, i: 40, d: 0.0, i_clamp: 1}
        Joint_2: {p: 80, i: 60, d: 0.0, i_clamp: 1}
        Joint_3: {p: 60, i: 40, d: 0.0, i_clamp: 1}
        Joint_4: {p: 60, i: 40, d: 0.0, i_clamp: 1}
        Joint_5: {p: 60, i: 40, d: 0.0, i_clamp: 1}
        Joint_6: {p: 80, i: 60, d: 0.0, i_clamp: 1}
      stop_trajectory_duration: 0.5
      state_publish_rate:  25
      action_monitor_rate: 10
      
    hand_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
        - Gripper_Idol_Gear_Joint
        - Gripper_Servo_Gear_Joint
      constraints:
        goal_time: 1.5
        stopped_velocity_tolerance: 0
        Gripper_Idol_Gear_Joint:       {trajectory: 0.0, goal: 0.0}
        #Tip_Gripper_Idol_Joint:        {trajectory: 0.0, goal: 0.0}
        Gripper_Servo_Gear_Joint:      {trajectory: 0.0, goal: 0.0}
        #Tip_Gripper_Servo_Joint:       {trajectory: 0.0, goal: 0.0}
        #Pivot_Arm_Gripper_Servo_Joint: {trajectory: 0.0, goal: 0.0}
        #Pivot_Arm_Gripper_Idol_Joint:  {trajectory: 0.0, goal: 0.0}
      gains:
        Gripper_Idol_Gear_Joint:       {p: 0, i: 0, d: 0, i_clamp: 0}
        #Tip_Gripper_Idol_Joint:        {p: 0, i: 0, d: 0, i_clamp: 0}
        Gripper_Servo_Gear_Joint:      {p: 0, i: 0, d: 0, i_clamp: 0}
        #Tip_Gripper_Servo_Joint:       {p: 0, i: 0, d: 0, i_clamp: 0}
        #Pivot_Arm_Gripper_Servo_Joint: {p: 0, i: 0, d: 0, i_clamp: 0}
        #Pivot_Arm_Gripper_Idol_Joint:  {p: 0, i: 0, d: 0, i_clamp: 0}
      stop_trajectory_duration: 1.0
      state_publish_rate:  1.0
      action_monitor_rate: 1.0