dof_fit:
    # Simulation settings for using moveit_sim_controllers
    moveit_sim_hw_interface:
      joint_model_group: hand
      joint_model_group_pose: open
    # ros_control_boilerplate Settings -----------------------
    # Settings for ros_control control loop
    generic_hw_control_loop:
      loop_hz: 300
      cycle_time_error_threshold: 0.01

    # Settings for ros_control hardware interface
    hardware_interface:
      joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
        - Joint_6
        - Gripper_Idol_Gear_Joint
        - Gripper_Servo_Gear_Joint
    sim_control_mode: 0 # 0: position, 1: velocity

    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - Joint_1
        - Joint_2
        - Joint_3
        - Joint_4
        - Joint_5
        - Joint_6

    hand_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - Gripper_Idol_Gear_Joint
        - Gripper_Servo_Gear_Joint
    
    # Position Controllers ---------------------------------------
    Joint_1_position_controller:
      type: effort_controllers/JointPositionController
      joint: Joint_1
      pid: {p: 60.0, i: 40.0, d: 0.0}
    Joint_2_position_controller:
      type: effort_controllers/JointPositionController
      joint: Joint_2
      pid: {p: 80.0, i: 60.0, d: 0.0}
    Joint_3_position_controller:
      type: effort_controllers/JointPositionController
      joint: Joint_3
      pid: {p: 60.0, i: 40.0, d: 0.0}
    Joint_4_position_controller:
      type: effort_controllers/JointPositionController
      joint: Joint_4
      pid: {p: 60.0, i: 40.0, d: 0.0}
    Joint_5_position_controller:
      type: effort_controllers/JointPositionController
      joint: Joint_5
      pid: {p: 60.0, i: 40.0, d: 0.0}
    Joint_6_position_controller:
      type: effort_controllers/JointPositionController
      joint: Joint_6
      pid: {p: 80.0, i: 60.0, d: 0.0}
    Gripper_Idol_Gear_Joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: Gripper_Idol_Gear_Joint
      pid: {p: 40.0, i: 40.0, d: 0.0}
    Gripper_Servo_Gear_Joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: Gripper_Servo_Gear_Joint
      pid: {p: 40.0, i: 40.0, d: 0.0}
